---
name: test

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-test
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      linux-amd64-artifact: ${{ steps.outputs.outputs.linux-amd64-artifact }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
      - id: build
        run: |
          GOOS=linux GOARCH=amd64 make dev
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: vault-plugin-secrets-openldap_linux_amd64
          path: bin/vault-plugin-secrets-openldap
          if-no-files-found: error
          retention-days: 1
      - id: outputs
        run: |
          echo "linux-amd64-artifact=vault-plugin-secrets-openldap_linux_amd64" | tee -a "$GITHUB_OUTPUT"

  scenarios:
    name: enos scenario
    needs: build
    uses: ./.github/workflows/run-sample.yml
    secrets: inherit
    with:
      sample-name: build_ent_linux_amd64_deb
      download: ${{ needs.build.outputs.linux-amd64-artifact }}
      max: 1

  completed-successfully:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - build
      - scenarios
    steps:
      - id: status
        name: Determine status
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            exit 1
          fi